FROM eclipse-temurin:22-jdk AS build
WORKDIR /workspace
COPY . .
RUN cp settings.backend.gradle.kts settings.gradle.kts
RUN ./gradlew --no-daemon :backend:app:installDist

FROM eclipse-temurin:22-jre
WORKDIR /app
COPY --from=build /workspace/backend/app/build/install/phoebe-backend /app
ENV PORT=80
EXPOSE 80
CMD ["/app/bin/phoebe-backend"]
