org.gradle.jvmargs=-Xmx6144m -Dfile.encoding=UTF-8 -XX:-UseOnStackReplacement
kotlin.native.jvmArgs=-Xmx6g
android.useAndroidX=true
kotlin.code.style=official
phoebe.versionName=2026.0705.1951
phoebe.versionCode=384
# use -Pphoebe.desktopProguard=true to enable.
phoebe.desktopProguard=false
phoebe.backend.url=https://phoebe-backend.vercel.app
