org.gradle.jvmargs=-Xmx6144m -Dfile.encoding=UTF-8 -XX:-UseOnStackReplacement
org.gradle.caching=true
org.gradle.parallel=true
kotlin.native.jvmArgs=-Xmx6g
android.useAndroidX=true
kotlin.code.style=official
phoebe.versionName=2026.0806.0123
phoebe.versionCode=409
# use -Pphoebe.desktopProguard=true to enable.
phoebe.desktopProguard=false
phoebe.backend.url=https://phoebe-backend.vercel.app
