package com.phoebe.app.ui

import androidx.compose.runtime.Composable
import com.phoebe.app.data.JellyfinQuickConnectResult
import com.phoebe.app.domain.Album
import com.phoebe.app.domain.AppScreen
import com.phoebe.app.domain.AppSettings
import com.phoebe.app.domain.Artist
import com.phoebe.app.domain.ArtistRadioAvailability
import com.phoebe.app.domain.CatalogSnapshot
import com.phoebe.app.domain.CollectionEntry
import com.phoebe.app.domain.HomeSection
import com.phoebe.app.domain.JellyfinLibraryPageKind
import com.phoebe.app.domain.JellyfinSyncMode
import com.phoebe.app.domain.LibraryColumnVisibility
import com.phoebe.app.domain.LibrarySortBy
import com.phoebe.app.domain.LibraryUiPreferences
import com.phoebe.app.domain.LyricsLoadState
import com.phoebe.app.domain.MediaProviderType
import com.phoebe.app.domain.MediaSourcesState
import com.phoebe.app.domain.MusicLibrary
import com.phoebe.app.domain.PersonalMixPreferences
import com.phoebe.app.domain.PlexRadioStation
import com.phoebe.app.domain.PlexServer
import com.phoebe.app.domain.PlexSession
import com.phoebe.app.domain.Playlist
import com.phoebe.app.domain.RepeatMode
import com.phoebe.app.domain.Track
import com.phoebe.app.domain.defaultCollectionEntries
import com.phoebe.app.player.CastState

internal data class DesktopShellState(
    val screen: AppScreen,
    val section: DesktopSection,
    val selectedPlaylistId: String?,
    val searchQuery: String,
    val libraryFilter: LibraryFilterTab,
    val showQueue: Boolean,
    val compact: Boolean,
    val busy: Boolean,
    val useLightAppearance: Boolean,
    val appearanceTintId: String,
    val settingsInitialCategory: SettingsCategory = SettingsCategory.AudioPlayback,
)

internal data class PlaybackUiState(
    val track: Track?,
    val upNext: List<Track>,
    val isPlaying: Boolean,
    val isBuffering: Boolean,
    val positionMs: Long,
    val bufferedPositionMs: Long,
    val currentIndex: Int,
    val shuffle: Boolean,
    val repeat: RepeatMode,
    val volume: Float,
    val castState: CastState = CastState(),
    val remotePlaybackTarget: String? = null,
    val lyricsTrack: Track? = null,
    val lyricsState: LyricsLoadState = LyricsLoadState.Idle,
)

internal data class BrowseUiState(
    val catalog: CatalogSnapshot,
    val catalogRefreshing: Boolean,
    val session: PlexSession?,
    val mediaSources: MediaSourcesState,
    val homeUiState: HomeUiState,
    val playHistory: PlayHistorySnapshot,
    val libraryUi: LibraryUiPreferences,
    val supportedCollectionEntries: Set<CollectionEntry> = defaultCollectionEntries.toSet(),
    val artistRadioAvailability: Map<String, ArtistRadioAvailability> = emptyMap(),
    val radioStartingIds: Set<String> = emptySet(),
    val radioStations: List<PlexRadioStation> = emptyList(),
    val decadeMixNotice: String? = null,
)

internal data class AuthSetupState(
    val appMessage: String,
    val pinCode: String?,
    val busy: Boolean,
    val serversLoading: Boolean = false,
    val jellyfinServers: List<PlexServer> = emptyList(),
    val jellyfinDiscoveryLoading: Boolean = false,
    val jellyfinQuickConnect: JellyfinQuickConnectResult? = null,
    val servers: List<PlexServer>,
    val libraries: List<MusicLibrary>,
    val librariesLoading: Boolean = false,
)

internal data class SettingsUiState(
    val appSettings: AppSettings,
    val downloadDirectory: String?,
    val downloadCount: Int,
    val defaultDownloadDirectoryLabel: String,
)

internal data class BrowseActions(
    val onNavigate: (DesktopSection) -> Unit,
    val onSearchQuery: (String) -> Unit,
    val onLibraryFilter: (LibraryFilterTab) -> Unit,
    val onPlaylist: (Playlist) -> Unit,
    val onArtist: (Artist) -> Unit,
    val onAlbum: (Album) -> Unit,
    val onSong: (Track) -> Unit,
    val onOpenLyrics: (Track) -> Unit = {},
    val onRecentSongs: () -> Unit,
    val onRecentArtists: () -> Unit,
    val onRecentAlbums: () -> Unit,
    val onFavoritePlaylists: () -> Unit = {},
    val onFavoriteArtists: () -> Unit = {},
    val onFavoriteAlbums: () -> Unit = {},
    val onRecentlyPlayed: () -> Unit,
    val onMostPlayed: () -> Unit,
    val onCollections: (CollectionEntry) -> Unit,
    val onCollectionValue: (CollectionEntry, String) -> Unit,
    val onRefreshRandomArtists: () -> Unit,
    val onRefreshRandomAlbums: () -> Unit,
    val onPrefetchHomeArtist: (Artist) -> Unit = {},
    val onPrefetchHomeAlbum: (Album) -> Unit = {},
    val onPlayDecadeMix: (Int) -> Unit = {},
    val onClearDecadeMixNotice: () -> Unit = {},
    val onPlayRadioStation: (PlexRadioStation) -> Unit = {},
    val onPopDetail: () -> Unit,
    val onPlayTracks: (List<Track>, Int) -> Unit,
    val onAddToUpNext: (Track) -> Unit,
    val onDownload: (Track) -> Unit,
    val onDownloadArtist: (Artist) -> Unit,
    val onProbeArtistRadio: (Artist) -> Unit = {},
    val onPlayArtistRadio: (Artist) -> Unit,
    val onDownloadAlbum: (Album) -> Unit,
    val onDownloadPlaylist: (Playlist) -> Unit,
    val onSignOut: () -> Unit,
    val onAddLocalFolder: (String?) -> Unit,
    val onRemoveLocalFolder: (String) -> Unit,
    val onToggleLocalFolder: (String, Boolean) -> Unit,
    val onRefreshLibrary: () -> Unit,
    val onJellyfinPage: (JellyfinLibraryPageKind, Int) -> Unit = { _, _ -> },
    val onLibrarySortBy: (LibrarySortBy) -> Unit,
    val onLibraryAscending: (Boolean) -> Unit,
    val onLibraryColumns: (LibraryColumnVisibility) -> Unit,
    val onHomeSections: (List<HomeSection>) -> Unit,
    val onPersonalMix: (PersonalMixPreferences) -> Unit,
    val onExportFavoritePlaylists: () -> Unit,
    val onImportFavoritePlaylists: () -> Unit,
)

internal data class PlaybackActions(
    val onToggle: () -> Unit,
    val onPrevious: () -> Unit,
    val onNext: () -> Unit,
    val onShuffle: () -> Unit,
    val onRepeat: () -> Unit,
    val onVolume: (Float) -> Unit,
    val onSeek: (Long) -> Unit,
    val onCast: () -> Unit = {},
    val onLyrics: () -> Unit = {},
    val onPlayQueue: (Int) -> Unit,
    val onClearQueue: () -> Unit,
    val onMoveUpNext: (Int, Int) -> Unit,
    val onRemoveUpNext: (Int) -> Unit,
)

internal data class AuthSetupActions(
    val onStartSignIn: () -> Unit,
    val onFinishSignIn: () -> Unit,
    val onSignInJellyfin: (String, String, String) -> Unit,
    val onSignInProvider: (MediaProviderType, String, String, String, JellyfinSyncMode?) -> Unit = { _, _, _, _, _ -> },
    val onDiscoverJellyfinServers: () -> Unit = {},
    val onStartJellyfinQuickConnect: (String) -> Unit = {},
    val onFinishJellyfinQuickConnect: () -> Unit = {},
    val onSelectServer: (PlexServer) -> Unit,
    val onSelectLibrary: (MusicLibrary, JellyfinSyncMode?) -> Unit,
    val onCancelPlexSetup: () -> Unit,
    val onBackToServerPicker: () -> Unit,
    val onRetryServers: () -> Unit,
)

internal data class SettingsActions(
    val onCrossfadeSeconds: (Int) -> Unit,
    val onScanLibraryOnLaunch: (Boolean) -> Unit,
    val onNotifyWhenDownloadFinishes: (Boolean) -> Unit,
    val onDownloadDirectory: (String?) -> Unit,
    val onDeleteAllDownloads: () -> Unit,
    val onUseLightAppearanceChange: (Boolean) -> Unit,
    val onAppearanceTintChange: (String) -> Unit,
    val onRetryLyrics: () -> Unit = {},
)

@Composable
internal fun DesktopPlayer(
    shellState: DesktopShellState,
    playbackState: PlaybackUiState,
    browseState: BrowseUiState,
    authSetupState: AuthSetupState,
    settingsState: SettingsUiState,
    browseActions: BrowseActions,
    playbackActions: PlaybackActions,
    authSetupActions: AuthSetupActions,
    settingsActions: SettingsActions,
) {
    DesktopPlayer(
        screen = shellState.screen,
        catalog = browseState.catalog,
        catalogRefreshing = browseState.catalogRefreshing,
        session = browseState.session,
        mediaSources = browseState.mediaSources,
        track = playbackState.track,
        homeUiState = browseState.homeUiState,
        playHistory = browseState.playHistory,
        upNext = playbackState.upNext,
        isPlaying = playbackState.isPlaying,
        isBuffering = playbackState.isBuffering,
        positionMs = playbackState.positionMs,
        bufferedPositionMs = playbackState.bufferedPositionMs,
        currentIndex = playbackState.currentIndex,
        lyricsTrack = playbackState.lyricsTrack,
        lyricsState = playbackState.lyricsState,
        section = shellState.section,
        selectedPlaylistId = shellState.selectedPlaylistId,
        searchQuery = shellState.searchQuery,
        libraryFilter = shellState.libraryFilter,
        libraryUi = browseState.libraryUi,
        appMessage = authSetupState.appMessage,
        pinCode = authSetupState.pinCode,
        shuffle = playbackState.shuffle,
        repeat = playbackState.repeat,
        volume = playbackState.volume,
        castState = playbackState.castState,
        remotePlaybackTarget = playbackState.remotePlaybackTarget,
        showQueue = shellState.showQueue,
        compact = shellState.compact,
        busy = authSetupState.busy,
        serversLoading = authSetupState.serversLoading,
        onNavigate = browseActions.onNavigate,
        onSearchQuery = browseActions.onSearchQuery,
        onLibraryFilter = browseActions.onLibraryFilter,
        onPlaylist = browseActions.onPlaylist,
        onArtist = browseActions.onArtist,
        onAlbum = browseActions.onAlbum,
        onSong = browseActions.onSong,
        onOpenLyrics = browseActions.onOpenLyrics,
        onRecentSongs = browseActions.onRecentSongs,
        onRecentArtists = browseActions.onRecentArtists,
        onRecentAlbums = browseActions.onRecentAlbums,
        onFavoritePlaylists = browseActions.onFavoritePlaylists,
        onFavoriteArtists = browseActions.onFavoriteArtists,
        onFavoriteAlbums = browseActions.onFavoriteAlbums,
        onRecentlyPlayed = browseActions.onRecentlyPlayed,
        onMostPlayed = browseActions.onMostPlayed,
        onCollections = browseActions.onCollections,
        onCollectionValue = browseActions.onCollectionValue,
        supportedCollectionEntries = browseState.supportedCollectionEntries,
        onRefreshRandomArtists = browseActions.onRefreshRandomArtists,
        onRefreshRandomAlbums = browseActions.onRefreshRandomAlbums,
        onPrefetchHomeArtist = browseActions.onPrefetchHomeArtist,
        onPrefetchHomeAlbum = browseActions.onPrefetchHomeAlbum,
        onPlayDecadeMix = browseActions.onPlayDecadeMix,
        decadeMixNotice = browseState.decadeMixNotice,
        onClearDecadeMixNotice = browseActions.onClearDecadeMixNotice,
        radioStations = browseState.radioStations,
        onPlayRadioStation = browseActions.onPlayRadioStation,
        onPopDetail = browseActions.onPopDetail,
        onToggle = playbackActions.onToggle,
        onPrevious = playbackActions.onPrevious,
        onNext = playbackActions.onNext,
        onShuffle = playbackActions.onShuffle,
        onRepeat = playbackActions.onRepeat,
        onVolume = playbackActions.onVolume,
        onSeek = playbackActions.onSeek,
        onCast = playbackActions.onCast,
        onLyrics = playbackActions.onLyrics,
        onPlayQueue = playbackActions.onPlayQueue,
        onClearQueue = playbackActions.onClearQueue,
        onMoveUpNext = playbackActions.onMoveUpNext,
        onRemoveUpNext = playbackActions.onRemoveUpNext,
        onPlayTracks = browseActions.onPlayTracks,
        onAddToUpNext = browseActions.onAddToUpNext,
        onDownload = browseActions.onDownload,
        onDownloadArtist = browseActions.onDownloadArtist,
        artistRadioAvailability = browseState.artistRadioAvailability,
        radioStartingIds = browseState.radioStartingIds,
        onProbeArtistRadio = browseActions.onProbeArtistRadio,
        onPlayArtistRadio = browseActions.onPlayArtistRadio,
        onDownloadAlbum = browseActions.onDownloadAlbum,
        onDownloadPlaylist = browseActions.onDownloadPlaylist,
        onStartSignIn = authSetupActions.onStartSignIn,
        onFinishSignIn = authSetupActions.onFinishSignIn,
        onSignInJellyfin = authSetupActions.onSignInJellyfin,
        onSignInProvider = authSetupActions.onSignInProvider,
        jellyfinServers = authSetupState.jellyfinServers,
        jellyfinDiscoveryLoading = authSetupState.jellyfinDiscoveryLoading,
        jellyfinQuickConnect = authSetupState.jellyfinQuickConnect,
        onDiscoverJellyfinServers = authSetupActions.onDiscoverJellyfinServers,
        onStartJellyfinQuickConnect = authSetupActions.onStartJellyfinQuickConnect,
        onFinishJellyfinQuickConnect = authSetupActions.onFinishJellyfinQuickConnect,
        onSignOut = browseActions.onSignOut,
        onAddLocalFolder = browseActions.onAddLocalFolder,
        onRemoveLocalFolder = browseActions.onRemoveLocalFolder,
        onToggleLocalFolder = browseActions.onToggleLocalFolder,
        onRefreshLibrary = browseActions.onRefreshLibrary,
        onJellyfinPage = browseActions.onJellyfinPage,
        servers = authSetupState.servers,
        libraries = authSetupState.libraries,
        librariesLoading = authSetupState.librariesLoading,
        onSelectServer = authSetupActions.onSelectServer,
        onSelectLibrary = authSetupActions.onSelectLibrary,
        onCancelPlexSetup = authSetupActions.onCancelPlexSetup,
        onBackToServerPicker = authSetupActions.onBackToServerPicker,
        onRetryServers = authSetupActions.onRetryServers,
        onLibrarySortBy = browseActions.onLibrarySortBy,
        onLibraryAscending = browseActions.onLibraryAscending,
        onLibraryColumns = browseActions.onLibraryColumns,
        onHomeSections = browseActions.onHomeSections,
        onPersonalMix = browseActions.onPersonalMix,
        onExportFavoritePlaylists = browseActions.onExportFavoritePlaylists,
        onImportFavoritePlaylists = browseActions.onImportFavoritePlaylists,
        appSettings = settingsState.appSettings,
        onCrossfadeSeconds = settingsActions.onCrossfadeSeconds,
        onScanLibraryOnLaunch = settingsActions.onScanLibraryOnLaunch,
        onNotifyWhenDownloadFinishes = settingsActions.onNotifyWhenDownloadFinishes,
        downloadDirectory = settingsState.downloadDirectory,
        downloadCount = settingsState.downloadCount,
        defaultDownloadDirectoryLabel = settingsState.defaultDownloadDirectoryLabel,
        onDownloadDirectory = settingsActions.onDownloadDirectory,
        onDeleteAllDownloads = settingsActions.onDeleteAllDownloads,
        useLightAppearance = shellState.useLightAppearance,
        onUseLightAppearanceChange = settingsActions.onUseLightAppearanceChange,
        appearanceTintId = shellState.appearanceTintId,
        onAppearanceTintChange = settingsActions.onAppearanceTintChange,
        settingsInitialCategory = shellState.settingsInitialCategory,
        onRetryLyrics = settingsActions.onRetryLyrics,
    )
}
