package com.phoebe.app.feature.settings

import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.ui.Modifier
import com.phoebe.app.domain.AppSettings
import com.phoebe.app.domain.AudioProcessingCapabilities
import com.phoebe.app.domain.AudioProcessingSettings
import com.phoebe.app.domain.DownloadItem
import com.phoebe.app.domain.DownloadPolicySettings
import com.phoebe.app.domain.HomeSection
import com.phoebe.app.domain.LibraryUiPreferences
import com.phoebe.app.domain.MobileBottomTab
import com.phoebe.app.domain.NowPlayingVisualizerPreset
import com.phoebe.app.domain.PersonalMixPreferences
import com.phoebe.app.domain.PlexSession
import com.phoebe.app.platform.SecureCredentialAvailability
import com.phoebe.app.ui.HomeScreenLayoutMode
import com.phoebe.app.updates.AppUpdateState

@Immutable
data class SettingsRouteState(
    val isLightMode: Boolean,
    val tintId: String,
    val downloadDirectory: String?,
    val downloadCount: Int,
    val downloadItems: List<DownloadItem> = emptyList(),
    val downloadManager: DownloadManagerUiSummary = DownloadManagerUiSummary(total = downloadCount, complete = downloadCount),
    val appSettings: AppSettings,
    val audioProcessingCapabilities: AudioProcessingCapabilities = AudioProcessingCapabilities(),
    val libraryUi: LibraryUiPreferences,
    val defaultDownloadDirectoryLabel: String,
    val homeScreenLayoutMode: HomeScreenLayoutMode = HomeScreenLayoutMode.Default,
    val session: PlexSession? = null,
    val listenBrainzCredentialAvailability: SecureCredentialAvailability = SecureCredentialAvailability.Unavailable,
    val initialCategory: SettingsCategory = SettingsCategory.AudioPlayback,
    val appUpdateState: AppUpdateState = AppUpdateState.Idle,
)

@Immutable
data class DownloadManagerUiSummary(
    val total: Int = 0,
    val active: Int = 0,
    val complete: Int = 0,
    val failed: Int = 0,
    val estimatedBytes: Long = 0L,
)

@Immutable
class SettingsRouteActions(
    val onLightModeChange: (Boolean) -> Unit,
    val onTintChange: (String) -> Unit,
    val onDownloadDirectory: (String?) -> Unit,
    val onDeleteAllDownloads: () -> Unit,
    val onDeleteCompletedDownloads: () -> Unit = {},
    val onClearFailedDownloads: () -> Unit = {},
    val onRetryFailedDownloads: () -> Unit = {},
    val onRetryDownloads: (Set<String>) -> Unit = {},
    val onCancelDownloads: (Set<String>) -> Unit = {},
    val onDeleteDownloads: (Set<String>) -> Unit = {},
    val onDownloadPolicySettings: (DownloadPolicySettings) -> Unit = {},
    val onCrossfadeSeconds: (Int) -> Unit,
    val onScanLibraryOnLaunch: (Boolean) -> Unit,
    val onNotifyWhenDownloadFinishes: (Boolean) -> Unit,
    val onKeepPlayingEnabled: (Boolean) -> Unit = {},
    val onPersistEqualizerSettings: (Boolean) -> Unit = {},
    val onPersistVolumeSettings: (Boolean) -> Unit = {},
    val onAudioProcessingSettings: (AudioProcessingSettings) -> Unit = {},
    val onVisualizerPreset: (NowPlayingVisualizerPreset) -> Unit = {},
    val onShowVisualizerInTvFrame: (Boolean) -> Unit = {},
    val onBlurredArtworkAppearance: (Boolean) -> Unit = {},
    val onFullBleedDetailArtwork: (Boolean) -> Unit = {},
    val onTintedBackgroundGradient: (Boolean) -> Unit = {},
    val onHomeSections: (List<HomeSection>) -> Unit,
    val onMobileBottomTabs: (List<MobileBottomTab>) -> Unit = {},
    val onPersonalMix: (PersonalMixPreferences) -> Unit,
    val onAlbumGridItemSize: (Int) -> Unit,
    val onArtistGridItemSize: (Int) -> Unit,
    val onExportFavoritePlaylists: () -> Unit,
    val onImportFavoritePlaylists: () -> Unit,
    val onExportRadioStations: () -> Unit,
    val onImportRadioStations: () -> Unit,
    val onExportBackupPackage: () -> Unit = {},
    val onImportBackupPackage: () -> Unit = {},
    val onReplaceFromBackupPackage: () -> Unit = {},
    val onHomeScreenLayoutModeChange: (HomeScreenLayoutMode) -> Unit = {},
    val onConnectListenBrainz: (String) -> Unit = {},
    val onDisconnectListenBrainz: () -> Unit = {},
    val onListenBrainzSubmitNowPlaying: (Boolean) -> Unit = {},
    val onListenBrainzSubmitListens: (Boolean) -> Unit = {},
    val onListenBrainzSubmitCurrentTrackFeedback: (Boolean) -> Unit = {},
    val onStartLastFmAuthorization: (String, String) -> Unit = { _, _ -> },
    val onFinishLastFmAuthorization: () -> Unit = {},
    val onDisconnectLastFm: () -> Unit = {},
    val onLastFmSubmitNowPlaying: (Boolean) -> Unit = {},
    val onLastFmSubmitScrobbles: (Boolean) -> Unit = {},
    val onCheckForUpdates: () -> Unit = {},
    val onInstallUpdate: () -> Unit = {},
)

@Composable
fun SettingsDesktopRoute(
    state: SettingsRouteState,
    actions: SettingsRouteActions,
    modifier: Modifier = Modifier,
) {
    SettingsDesktopView(
        isLightMode = state.isLightMode,
        onLightModeChange = actions.onLightModeChange,
        tintId = state.tintId,
        onTintChange = actions.onTintChange,
        downloadDirectory = state.downloadDirectory,
        downloadCount = state.downloadCount,
        downloadItems = state.downloadItems,
        downloadManager = state.downloadManager,
        appSettings = state.appSettings,
        audioProcessingCapabilities = state.audioProcessingCapabilities,
        libraryUi = state.libraryUi,
        defaultDownloadDirectoryLabel = state.defaultDownloadDirectoryLabel,
        onDownloadDirectory = actions.onDownloadDirectory,
        onDeleteAllDownloads = actions.onDeleteAllDownloads,
        onDeleteCompletedDownloads = actions.onDeleteCompletedDownloads,
        onClearFailedDownloads = actions.onClearFailedDownloads,
        onRetryFailedDownloads = actions.onRetryFailedDownloads,
        onRetryDownloads = actions.onRetryDownloads,
        onCancelDownloads = actions.onCancelDownloads,
        onDeleteDownloads = actions.onDeleteDownloads,
        onDownloadPolicySettings = actions.onDownloadPolicySettings,
        onCrossfadeSeconds = actions.onCrossfadeSeconds,
        onScanLibraryOnLaunch = actions.onScanLibraryOnLaunch,
        onNotifyWhenDownloadFinishes = actions.onNotifyWhenDownloadFinishes,
        onKeepPlayingEnabled = actions.onKeepPlayingEnabled,
        onPersistEqualizerSettings = actions.onPersistEqualizerSettings,
        onPersistVolumeSettings = actions.onPersistVolumeSettings,
        onAudioProcessingSettings = actions.onAudioProcessingSettings,
        onVisualizerPreset = actions.onVisualizerPreset,
        onShowVisualizerInTvFrame = actions.onShowVisualizerInTvFrame,
        onBlurredArtworkAppearance = actions.onBlurredArtworkAppearance,
        onFullBleedDetailArtwork = actions.onFullBleedDetailArtwork,
        onTintedBackgroundGradient = actions.onTintedBackgroundGradient,
        onHomeSections = actions.onHomeSections,
        onMobileBottomTabs = actions.onMobileBottomTabs,
        onPersonalMix = actions.onPersonalMix,
        onAlbumGridItemSize = actions.onAlbumGridItemSize,
        onArtistGridItemSize = actions.onArtistGridItemSize,
        onExportFavoritePlaylists = actions.onExportFavoritePlaylists,
        onImportFavoritePlaylists = actions.onImportFavoritePlaylists,
        onExportRadioStations = actions.onExportRadioStations,
        onImportRadioStations = actions.onImportRadioStations,
        onExportBackupPackage = actions.onExportBackupPackage,
        onImportBackupPackage = actions.onImportBackupPackage,
        onReplaceFromBackupPackage = actions.onReplaceFromBackupPackage,
        homeScreenLayoutMode = state.homeScreenLayoutMode,
        onHomeScreenLayoutModeChange = actions.onHomeScreenLayoutModeChange,
        session = state.session,
        listenBrainzCredentialAvailability = state.listenBrainzCredentialAvailability,
        onConnectListenBrainz = actions.onConnectListenBrainz,
        onDisconnectListenBrainz = actions.onDisconnectListenBrainz,
        onListenBrainzSubmitNowPlaying = actions.onListenBrainzSubmitNowPlaying,
        onListenBrainzSubmitListens = actions.onListenBrainzSubmitListens,
        onListenBrainzSubmitCurrentTrackFeedback = actions.onListenBrainzSubmitCurrentTrackFeedback,
        onStartLastFmAuthorization = actions.onStartLastFmAuthorization,
        onFinishLastFmAuthorization = actions.onFinishLastFmAuthorization,
        onDisconnectLastFm = actions.onDisconnectLastFm,
        onLastFmSubmitNowPlaying = actions.onLastFmSubmitNowPlaying,
        onLastFmSubmitScrobbles = actions.onLastFmSubmitScrobbles,
        appUpdateState = state.appUpdateState,
        onCheckForUpdates = actions.onCheckForUpdates,
        onInstallUpdate = actions.onInstallUpdate,
        modifier = modifier,
        initialCategory = state.initialCategory,
    )
}

@Composable
fun SettingsMobileRoute(
    state: SettingsRouteState,
    actions: SettingsRouteActions,
    modifier: Modifier = Modifier,
) {
    SettingsMobileView(
        isLightMode = state.isLightMode,
        onLightModeChange = actions.onLightModeChange,
        tintId = state.tintId,
        onTintChange = actions.onTintChange,
        downloadDirectory = state.downloadDirectory,
        downloadCount = state.downloadCount,
        downloadItems = state.downloadItems,
        downloadManager = state.downloadManager,
        appSettings = state.appSettings,
        audioProcessingCapabilities = state.audioProcessingCapabilities,
        libraryUi = state.libraryUi,
        defaultDownloadDirectoryLabel = state.defaultDownloadDirectoryLabel,
        onDownloadDirectory = actions.onDownloadDirectory,
        onDeleteAllDownloads = actions.onDeleteAllDownloads,
        onDeleteCompletedDownloads = actions.onDeleteCompletedDownloads,
        onClearFailedDownloads = actions.onClearFailedDownloads,
        onRetryFailedDownloads = actions.onRetryFailedDownloads,
        onRetryDownloads = actions.onRetryDownloads,
        onCancelDownloads = actions.onCancelDownloads,
        onDeleteDownloads = actions.onDeleteDownloads,
        onDownloadPolicySettings = actions.onDownloadPolicySettings,
        onCrossfadeSeconds = actions.onCrossfadeSeconds,
        onScanLibraryOnLaunch = actions.onScanLibraryOnLaunch,
        onNotifyWhenDownloadFinishes = actions.onNotifyWhenDownloadFinishes,
        onKeepPlayingEnabled = actions.onKeepPlayingEnabled,
        onPersistEqualizerSettings = actions.onPersistEqualizerSettings,
        onPersistVolumeSettings = actions.onPersistVolumeSettings,
        onAudioProcessingSettings = actions.onAudioProcessingSettings,
        onVisualizerPreset = actions.onVisualizerPreset,
        onShowVisualizerInTvFrame = actions.onShowVisualizerInTvFrame,
        onBlurredArtworkAppearance = actions.onBlurredArtworkAppearance,
        onTintedBackgroundGradient = actions.onTintedBackgroundGradient,
        onHomeSections = actions.onHomeSections,
        onMobileBottomTabs = actions.onMobileBottomTabs,
        onPersonalMix = actions.onPersonalMix,
        onAlbumGridItemSize = actions.onAlbumGridItemSize,
        onArtistGridItemSize = actions.onArtistGridItemSize,
        onExportFavoritePlaylists = actions.onExportFavoritePlaylists,
        onImportFavoritePlaylists = actions.onImportFavoritePlaylists,
        onExportRadioStations = actions.onExportRadioStations,
        onImportRadioStations = actions.onImportRadioStations,
        onExportBackupPackage = actions.onExportBackupPackage,
        onImportBackupPackage = actions.onImportBackupPackage,
        onReplaceFromBackupPackage = actions.onReplaceFromBackupPackage,
        homeScreenLayoutMode = state.homeScreenLayoutMode,
        onHomeScreenLayoutModeChange = actions.onHomeScreenLayoutModeChange,
        session = state.session,
        listenBrainzCredentialAvailability = state.listenBrainzCredentialAvailability,
        onConnectListenBrainz = actions.onConnectListenBrainz,
        onDisconnectListenBrainz = actions.onDisconnectListenBrainz,
        onListenBrainzSubmitNowPlaying = actions.onListenBrainzSubmitNowPlaying,
        onListenBrainzSubmitListens = actions.onListenBrainzSubmitListens,
        onListenBrainzSubmitCurrentTrackFeedback = actions.onListenBrainzSubmitCurrentTrackFeedback,
        onStartLastFmAuthorization = actions.onStartLastFmAuthorization,
        onFinishLastFmAuthorization = actions.onFinishLastFmAuthorization,
        onDisconnectLastFm = actions.onDisconnectLastFm,
        onLastFmSubmitNowPlaying = actions.onLastFmSubmitNowPlaying,
        onLastFmSubmitScrobbles = actions.onLastFmSubmitScrobbles,
        appUpdateState = state.appUpdateState,
        onCheckForUpdates = actions.onCheckForUpdates,
        onInstallUpdate = actions.onInstallUpdate,
        modifier = modifier,
    )
}
